version: "3"

services:
    api:
        build: .
        ports:
            - "8000:8080"
        environment:
            DATABASE.HOST: db
            DATABASE.PORT: 5432
            DATABASE.NAME: covid-db
            DATABASE.USER: postgres
            DATABASE.PASSWORD: postgres
        depends_on:
            - db
    db:
        image: postgres:14
        container_name: db
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
            POSTGRES_DB: covid-db
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data:
