spring:
    jpa:
        database: h2
    datasource:
        url: jdbc:h2:mem:AZ
        driver-class-name: org.h2.Driver
    h2:
        console:
            enabled: true
    liquibase:
        enabled: false
        change-log: "classpath:db/changelog/dbchangelog.xml"
    management:
    endpoints:
        web:
            exposure:
                include: health,info,prometheus,metrics
