spring:
  datasource:
    url: jdbc:postgresql://db:5432/covid-db
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
    change-log: "classpath:db/changelog/dbchangelog.xml"
  management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
